# Generated by Django 3.2.7 on 2021-10-07 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('identity_document', models.IntegerField(unique=True, verbose_name='Identity Document')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=80, unique=True, verbose_name='Email')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='Address')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Username')),
                ('phone_number', models.CharField(max_length=15, null=True, verbose_name='Phone Number')),
                ('admin', models.BooleanField(default=False)),
                ('image', models.ImageField(null=True, upload_to='users')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('pet_type', models.CharField(choices=[('P', 'Perro'), ('G', 'Gato'), ('C', 'Conejo'), ('H', 'Hamster'), ('A', 'Ave')], max_length=10)),
                ('pet_gender', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=10)),
                ('pet_name', models.CharField(max_length=20)),
                ('pet_age', models.PositiveIntegerField()),
                ('pet_breed', models.CharField(max_length=20)),
                ('pet_city', models.CharField(max_length=20)),
                ('photo', models.URLField()),
                ('date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pqrs',
            fields=[
                ('pqrs_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('adoption_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('post_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adopted', to='adoptLifeApp.post')),
            ],
        ),
    ]
