# Generated by Django 3.2.7 on 2021-10-27 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptLifeApp', '0007_auto_20211014_2022'),
        ('adoptLifeApp', '0007_auto_20211022_2037'),
    ]

    operations = [
    ]
